#!/bin/bash

# Vamos fazer manobras simples com todas as versoes de CISIS:
#	id2i CDS.id create=CDS
#	mx CDS now -all
#	mx CDS iso=CDS.iso now -all
#	mx iso=CDS.iso create=CDS now -all
#	mx CDS "fst=@" fullinv=CDS
#	mx dict=CDS now -all
#	mx CDS "water * plants" now
#	mx CDS "text=water" now
#	wxis IsisScript=teste01.xis db=CDS
#		mfnrange
#		keyrange
#		search

# Codigo .xis utilizado
#
#<IsisScript name="teste01">
#<section name="main">
#
# <field action="cgi" tag="5000">db</field>
#
# <display>Percorrendo 10 registros...
#</display>
# <do task="mfnrange">
#	<parm name="db"><pft>v5000</pft></parm>
#	<parm name="from">1</parm>
#	<parm name="to">10</parm>
#	<loop>
#		<!-- display><pft>mfn(3),' '</pft></display -->
#	</loop>
# </do>
# <display>Percorrendo o IF...
#</display>
# <do task="keyrange">
#	<field action="define" tag="1000">Isis_Key</field>
#	<field action="define" tag="1001">Isis_Current</field>
#	<field action="define" tag="1002">Isis_Total</field>
#	<field action="define" tag="1031">Isis_From</field>
#	<field action="define" tag="1091">Isis_Status</field>
#	<field action="define" tag="1092">Isis_ErrorInfo</field>
#	<parm name="db"><pft>v5000</pft></parm>
#	<parm name="from">A</parm>
#	<parm name="to">ZZZZ</parm>
#	<loop>
#		<display><pft>v1000/</pft></display>
#	</loop>
# </do>
#
# <display>Efetuando uma busca...
#</display>
# <do task="search">
#	<field action="define" tag="1001">Isis_Current</field>
#	<field action="define" tag="1002">Isis_Total</field>
#	<field action="define" tag="1031">Isis_From</field>
#	<field action="define" tag="1091">Isis_Status</field>
#	<field action="define" tag="1092">Isis_ErrorInfo</field>
#	<parm name="db"><pft>v5000</pft></parm>
#	<parm name="expression">water * plants</parm>
#	<loop>
#		<display><pft>mfn(3)/</pft></display>
#	</loop>
# </do>
#
#</section>
#</IsisScript>
#

# Ajusta versão em teste
#for i in BigIsis ffi ffi1660 ffi512 ffi512G4 ffiG4 ffiG4_4 isis isis1660 isisG lind lind512 lind512G4 lindG4
#for i in isis isis1660 lind ffi lindG4 ffiG4

#  entrada: parametros com o nome das versoes a serem testadas
#    saida: console out com o resultado de execucao
# corrente: .
#  chamada: teste03.sh [-h|-V|--changelog] [parm1] [parm2] [parm3] .. [parmN]
#  exemplo: ./teste03.sh isis isis1660 lind ffi1660 ffi lindG4 ffiG4
#    notas: deve estar disponivel no diretorio corrente o arquivo CDS.id e
#           as versoes a serem testadas (conforme parmX) no diretorio VUT
# -------------------------------------------------------------------------- #
#  Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde
#     é um centro especialidado da Organização Pan-Americana da Saúde,
#           escritório regional da Organização Mundial da Saúde
#                        BIREME / OPS / OMS (P)2014
# -------------------------------------------------------------------------- #
# Historico
# versao data, Responsavel
#	- Descricao
cat > /dev/null <<HISTORICO
vrs:  0.00 20140515, FJLopes
	- Edicao original
vrs:  0.01 20140516, FJLopes
	- Aprimoramento da chamada do comando
HISTORICO

# Anotacoes de inicio de processamento
CURRD=$(pwd)
HINIC=$(date '+%s')
HRINI=$(date '+%Y.%m.%d %H:%M:%S')
_DIA_=$(date '+%d')
_MES_=$(date '+%m')
_ANO_=$(date '+%Y')
TREXE=$(basename $0)
PRGDR=$(dirname $0)
LCORI=$*

#        1         2         3         4         5         6         7         8
#2345678901234567890123456789012345678901234567890123456789012345678901234567890
AJUDA_USO="
Uso: $TREXE [-h|-V|--changelog] [PARM1] [PARM2] .. [PARMn]

OPCOES:
 -h, --help             Exibe este texto de ajuda e para a execucao
 -V, --version          Exibe a versao corrente do comando e para a execucao
 -d, --debug  NIVEL     Define nivel de depuracao com valor numerico positivo
 --changelog            Exibe o historico de alteracoes

PARAMETROS:
 PARM1   diretorio com a versao a testar ou arquivo com a lista de versoes
 PARM2   diretorio com a versao a testar
 PARMn   diretorio com a versao a testar
"

while test -n "$1"
do
	case "$1" in
		-h | --help)
			echo "$AJUDA_USO"
			exit
		;;

	-V | --version)
			echo -e -n "\n$TREXE "
			grep '^vrs: ' $PRGDR/$TREXE | tail -1
			echo
			exit
		;;

	-d | --debug)
		shift
		isNumber $1
		[ $? -ne 0 ] && echo -e "\n$TREXE: O argumento da opcao DEBUG deve existir e ser numerico.\n$AJUDA_USO" && exit 2
		DEBUG=$1
		;;

	--changelog)
		TOTLN=$(wc -l $0 | awk '{ print $1 }')
		INILN=$(grep -n "<SPICEHAM" $0 | tail -1 | cut -d ":" -f "1")
		LINHAI=$(expr $TOTLN - $INILN)
		LINHAF=$(expr $LINHAI - 2)
		echo -e -n "\n$TREXE "
		grep '^vrs: ' $PRGDR/$TREXE | tail -1
		echo -n "==> "
		tail -$LINHAI $0 | head -$LINHAF
		echo
		unset	TOTLN	INILN	LINHAI	LINHAF
		exit
		;;

	*)
		if [ $(expr index "$1" "-") -ne 1 ]; then
			if test -z "$PARM1";  then PARM1=$1;  shift; continue; fi
			if test -z "$PARM2";  then PARM2=$1;  shift; continue; fi
			if test -z "$PARM3";  then PARM3=$1;  shift; continue; fi
			if test -z "$PARM4";  then PARM4=$1;  shift; continue; fi
			if test -z "$PARM5";  then PARM5=$1;  shift; continue; fi
			if test -z "$PARM6";  then PARM6=$1;  shift; continue; fi
			if test -z "$PARM7";  then PARM7=$1;  shift; continue; fi
			if test -z "$PARM8";  then PARM8=$1;  shift; continue; fi
			if test -z "$PARM9";  then PARM9=$1;  shift; continue; fi
			if test -z "$PARM10"; then PARM10=$1; shift; continue; fi
			if test -z "$PARM11"; then PARM11=$1; shift; continue; fi
			if test -z "$PARM12"; then PARM12=$1; shift; continue; fi
			if test -z "$PARM13"; then PARM13=$1; shift; continue; fi
			if test -z "$PARM14"; then PARM14=$1; shift; continue; fi
			if test -z "$PARM15"; then PARM15=$1; shift; continue; fi
			if test -z "$PARM16"; then PARM16=$1; shift; continue; fi
			if test -z "$PARM17"; then PARM17=$1; shift; continue; fi
			if test -z "$PARM18"; then PARM18=$1; shift; continue; fi
			if test -z "$PARM19"; then PARM19=$1; shift; continue; fi
			if test -z "$PARM20"; then PARM20=$1; shift; continue; fi
		else
			echo "Opcao nao valida: ($1)"
		fi
		;;
	esac
	# Argumento tratado, desloca os parametros e trata o proximo
	shift
done

if [ -z "$PARM1" ]; then
	PARM1="isis"
fi

for i in $PARM1 $PARM2 $PARM3 $PARM4 $PARM5 $PARM6 $PARM7 $PARM8 $PARM9 $PARM10 $PARM11 $PARM12 $PARM13 $PARM14 $PARM15 $PARM16 $PARM17 $PARM18 $PARM12 $PARM19 $PARM20
do
	export CISIS_DIR=linux64/$i
	echo "-------------------------------------------------------"
	echo "Iniciando teste com $CISIS_DIR"
	echo 
	$CISIS_DIR/mx what
	$CISIS_DIR/id2i CDS.id create=CDS
	if [ $? != 0 ]; then echo "Erro $i. Carregando .ID"; exit 1; fi
	$CISIS_DIR/mx CDS now -all
	if [ $? != 0 ]; then echo "Erro $i. Lendo MF"; exit 1; fi
	$CISIS_DIR/mx CDS iso=CDS.iso now -all
	if [ $? != 0 ]; then echo "Erro $i. Gerando ISO"; exit 1; fi
	$CISIS_DIR/mx iso=CDS.iso create=CDS now -all
	if [ $? != 0 ]; then echo "Erro $i. Carregando ISO"; exit 1; fi
	$CISIS_DIR/mx CDS "fst=@" fullinv=CDS
	if [ $? != 0 ]; then echo "Erro $i. Gerando IF"; exit 1; fi
	$CISIS_DIR/mx dict=CDS now -all
	if [ $? != 0 ]; then echo "Erro $i. Lendo IF"; exit 1; fi
	$CISIS_DIR/mx CDS "water * plants" now
	if [ $? != 0 ]; then echo "Erro $i. Busca booleana"; exit 1; fi
	$CISIS_DIR/mx CDS "text=water" now
	if [ $? != 0 ]; then echo "Erro $i. Busca livre"; exit 1; fi
	$CISIS_DIR/wxis IsisScript=teste01.xis db=CDS
	if [ $? != 0 ]; then echo "Erro $i. Uso do WWWISIS"; exit 1; fi
	echo
done
unset CISIS_DIR
# -------------------------------------------------------------------------- #
cat > /dev/null <<SPICEDHAM
CHANGELOG
20140515 Edicao original
20140515 Insercao de opcoes de execucao
	 - mini-help
	 - exibicao de Versao
	 - exsibicao de changelog	 
SPICEDHAM

